{
 "title": "Kubernetes / Compute Resources / Node (Pods)",
 "tags": [
  "ZKube",
  "generated"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum by (pod) (sum by (cluster, namespace, pod, container) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\"}[5m])) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (pod) (sum by (cluster, namespace, pod, container) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\"}[5m])) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})))"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_requests{resource=\"cpu\", job=\"kube-state-metrics\", cluster=\"$cluster\", node=~\"$node\"} * on (namespace, pod, cluster) group_left() max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))"
    },
    {
     "expr": "sum by (pod) (sum by (cluster, namespace, pod, container) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\"}[5m])) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"}))) / sum by (pod) (kube_pod_container_resource_requests{resource=\"cpu\", job=\"kube-state-metrics\", cluster=\"$cluster\", node=~\"$node\"} * on (namespace, pod, cluster) group_left() max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", job=\"kube-state-metrics\", cluster=\"$cluster\", node=~\"$node\"} * on (namespace, pod, cluster) group_left() max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))"
    },
    {
     "expr": "sum by (pod) (sum by (cluster, namespace, pod, container) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\"}[5m])) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"}))) / sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", job=\"kube-state-metrics\", cluster=\"$cluster\", node=~\"$node\"} * on (namespace, pod, cluster) group_left() max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))"
    }
   ]
  },
  {
   "title": "Memory Usage (w/cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\", container!=\"\"} * on (cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", job=\"kube-state-metrics\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum by (pod) (container_memory_rss{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\", container!=\"\"} * on (cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\", container!=\"\"} * on (cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})))"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\", job=\"kube-state-metrics\", cluster=\"$cluster\", node=~\"$node\"} * on (namespace, pod, cluster) group_left() max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\", container!=\"\"} * on (cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"}))) / sum by (pod) (kube_pod_container_resource_requests{resource=\"memory\", job=\"kube-state-metrics\", cluster=\"$cluster\", node=~\"$node\"} * on (namespace, pod, cluster) group_left() max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", job=\"kube-state-metrics\", cluster=\"$cluster\", node=~\"$node\"} * on (namespace, pod, cluster) group_left() max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\", container!=\"\"} * on (cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"}))) / sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", job=\"kube-state-metrics\", cluster=\"$cluster\", node=~\"$node\"} * on (namespace, pod, cluster) group_left() max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))"
    },
    {
     "expr": "sum by (pod) (container_memory_rss{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\", container!=\"\"} * on (cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})))"
    },
    {
     "expr": "sum by (pod) (container_memory_cache{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\", container!=\"\"} * on (cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})))"
    },
    {
     "expr": "sum by (pod) (container_memory_swap{job=\"kubelet\", image!=\"\", cluster=\"$cluster\", node=~\"$node\", container!=\"\"} * on (cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})))"
    }
   ]
  }
 ]
}