{
 "title": "Kubernetes / USE Method / Node(Windows)",
 "tags": [
  "ZKube",
  "generated"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kubernetes-windows-exporter\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(windows_system_system_up_time{cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg by (cluster, instance) ( rate(windows_cpu_time_total{job=\"kubernetes-windows-exporter\",mode=\"idle\"}[1m]) )){cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Usage Per Core",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (core) (irate(windows_cpu_time_total{cluster=\"$cluster\", job=\"kubernetes-windows-exporter\", mode!=\"idle\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - ((sum by (cluster, instance) ( (windows_memory_available_bytes{job=\"kubernetes-windows-exporter\"}) )) / (sum by (cluster, instance) ( windows_os_visible_memory_bytes{job=\"kubernetes-windows-exporter\"} )))){cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  windows_os_visible_memory_bytes{cluster=\"$cluster\", job=\"kubernetes-windows-exporter\", instance=\"$instance\"}\n  - windows_memory_available_bytes{cluster=\"$cluster\", job=\"kubernetes-windows-exporter\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(((windows_memory_cache_bytes{job=\"kubernetes-windows-exporter\"} + windows_memory_modified_page_list_bytes{job=\"kubernetes-windows-exporter\"} + windows_memory_standby_cache_core_bytes{job=\"kubernetes-windows-exporter\"} + windows_memory_standby_cache_normal_priority_bytes{job=\"kubernetes-windows-exporter\"} + windows_memory_standby_cache_reserve_bytes{job=\"kubernetes-windows-exporter\"})){cluster=\"$cluster\", instance=\"$instance\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(windows_memory_available_bytes{cluster=\"$cluster\", job=\"kubernetes-windows-exporter\", instance=\"$instance\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O) Pages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(irate(windows_memory_swap_page_operations_total{job=\"kubernetes-windows-exporter\"}[5m])){cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Swap IO"
    }
   ]
  },
  {
   "title": "Disk IO Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg by (cluster, instance) ( (irate(windows_logical_disk_read_seconds_total{job=\"kubernetes-windows-exporter\"}[1m]) + irate(windows_logical_disk_write_seconds_total{job=\"kubernetes-windows-exporter\"}[1m])) )){cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rate(windows_logical_disk_read_bytes_total{cluster=\"$cluster\", job=\"kubernetes-windows-exporter\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(windows_logical_disk_write_bytes_total{cluster=\"$cluster\", job=\"kubernetes-windows-exporter\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "written"
    },
    {
     "expr": "max(rate(windows_logical_disk_read_seconds_total{cluster=\"$cluster\", job=\"kubernetes-windows-exporter\",  instance=\"$instance\"}[$__rate_interval]) + rate(windows_logical_disk_write_seconds_total{cluster=\"$cluster\", job=\"kubernetes-windows-exporter\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max by (cluster,instance,volume)( (windows_logical_disk_size_bytes{job=\"kubernetes-windows-exporter\"} - windows_logical_disk_free_bytes{job=\"kubernetes-windows-exporter\"}) / windows_logical_disk_size_bytes{job=\"kubernetes-windows-exporter\"} )){cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by (cluster, instance) ( (irate(windows_net_bytes_total{job=\"kubernetes-windows-exporter\"}[1m])) )){cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by (cluster, instance) ( (irate(windows_net_packets_received_discarded_total{job=\"kubernetes-windows-exporter\"}[1m]) + irate(windows_net_packets_outbound_discarded_total{job=\"kubernetes-windows-exporter\"}[1m])) )){cluster=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}